/**
 * Generates seed/seed.sql with a freshly hashed bootstrap password.
 *
 * The hash format and iteration count must match worker/lib/crypto.ts exactly —
 * Cloudflare Workers' WebCrypto refuses PBKDF2 iteration counts above 100,000,
 * so a higher value here would produce a hash the deployed worker cannot verify.
 *
 * Bootstrap rows use stable ids, so re-running this rotates the password rather
 * than creating a second organization.
 *
 * Usage: node scripts/make-seed.mjs [password]
 */
import { webcrypto as crypto } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";

const PBKDF2_ITERATIONS = 100_000;

/** Crockford base32 as used by ULID: no I, L, O or U. */
const CROCKFORD = /^[0-9A-HJKMNP-TV-Z]{26}$/;

function stableId(prefix, body) {
  const padded = body.padEnd(26, "0");
  if (!CROCKFORD.test(padded)) throw new Error(`invalid ULID body for ${prefix}: ${padded}`);
  return `${prefix}_${padded}`;
}

const ORG_ID = stableId("org", "0AYNXZMERDEFA");
const ADMIN_ID = stableId("usr", "0AYNXZMERADMN");
const AUDITOR_ID = stableId("usr", "0AYNXZMERADTR");
const traineeId = (i) => stableId("trn", `0AYNXZMERTRN${String(i).padStart(2, "0")}`);

const b64 = (buf) => Buffer.from(buf).toString("base64");

async function hashPassword(password) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const keyMaterial = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(password),
    "PBKDF2",
    false,
    ["deriveBits"],
  );
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt, iterations: PBKDF2_ITERATIONS, hash: "SHA-256" },
    keyMaterial,
    256,
  );
  return `pbkdf2$${PBKDF2_ITERATIONS}$${b64(salt)}$${b64(bits)}`;
}

function randomPassword() {
  // Ambiguous glyphs (0/O, 1/l/I) left out so the password can be read aloud.
  const alphabet = "abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  const bytes = crypto.getRandomValues(new Uint8Array(20));
  return [...bytes].map((b) => alphabet[b % alphabet.length]).join("");
}

/** Sample roster mirrors the approved mockup so demos look familiar. */
const SAMPLE = [
  ["AZ-0241", "佐藤 美咲", "人事部", "misaki.sato@example.co.jp"],
  ["AZ-0248", "高橋 健太", "営業部", "kenta.takahashi@example.co.jp"],
  ["AZ-0250", "鈴木 彩香", "総務部", "ayaka.suzuki@example.co.jp"],
  ["AZ-0255", "田中 翔太", "情報システム部", "shota.tanaka@example.co.jp"],
  ["AZ-0257", "伊藤 葵", "経理部", "aoi.ito@example.co.jp"],
  ["AZ-0262", "渡辺 蓮", "営業部", "ren.watanabe@example.co.jp"],
];

const esc = (v) => (v == null ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);

const password = process.argv[2] || randomPassword();
const hash = await hashPassword(password);
const now = Date.now();

const lines = [
  "-- Ayonix Zoomer bootstrap seed. Generated by scripts/make-seed.mjs.",
  "-- Idempotent: stable ids, and re-running rotates the bootstrap password.",
  "",
  "INSERT OR IGNORE INTO organizations (id, name, timezone, locale, created_at, updated_at)",
  `VALUES (${esc(ORG_ID)}, ${esc("Ayonix 株式会社")}, 'Asia/Tokyo', 'ja', ${now}, ${now});`,
  "",
  "INSERT OR IGNORE INTO users (id, organization_id, email, name, role, password_hash, created_at, updated_at)",
  `VALUES (${esc(ADMIN_ID)}, ${esc(ORG_ID)}, ${esc("admin@ayonix.com")}, ${esc("システム管理者")}, 'sys_admin', ${esc(hash)}, ${now}, ${now});`,
  "",
  "INSERT OR IGNORE INTO users (id, organization_id, email, name, role, password_hash, created_at, updated_at)",
  `VALUES (${esc(AUDITOR_ID)}, ${esc(ORG_ID)}, ${esc("auditor@ayonix.com")}, ${esc("監査担当者")}, 'auditor', ${esc(hash)}, ${now}, ${now});`,
  "",
  "-- Rotate rather than duplicate when the seed is re-applied.",
  `UPDATE users SET password_hash = ${esc(hash)}, updated_at = ${now} WHERE id IN (${esc(ADMIN_ID)}, ${esc(AUDITOR_ID)});`,
  "",
  "INSERT OR IGNORE INTO monitoring_settings (organization_id, version, reauth_interval_sec, match_threshold, absence_sec, eyes_closed_sec, multi_face_frames, evidence_interval_sec, evidence_retention_days, precheck_max_attempts, liveness_required, image_quality, updated_at)",
  `VALUES (${esc(ORG_ID)}, 1, 60, 0.82, 60, 10, 15, 300, 30, 3, 1, 0.72, ${now});`,
  "",
];

SAMPLE.forEach(([ext, name, dept, email], i) => {
  lines.push(
    "INSERT OR IGNORE INTO trainees (id, organization_id, external_id, name, department, email, status, created_at, updated_at)",
    `VALUES (${esc(traineeId(i))}, ${esc(ORG_ID)}, ${esc(ext)}, ${esc(name)}, ${esc(dept)}, ${esc(email)}, 'ACTIVE', ${now}, ${now});`,
    "",
  );
});

mkdirSync("seed", { recursive: true });
writeFileSync("seed/seed.sql", lines.join("\n"));

mkdirSync(".secrets", { recursive: true });
writeFileSync(
  ".secrets/bootstrap.txt",
  [
    "Ayonix Zoomer bootstrap credentials",
    "-----------------------------------",
    `organization_id : ${ORG_ID}`,
    `admin           : admin@ayonix.com  (sys_admin)`,
    `auditor         : auditor@ayonix.com  (read-only)`,
    `password        : ${password}`,
    "",
    "Change this password after first sign-in.",
  ].join("\n"),
);

console.log(`seed written. organization=${ORG_ID}`);
console.log(`admin=admin@ayonix.com password=${password}`);
